# Day_26 < Working with APIs (requests) >

import requests

API_KEY = "9444d2efa8116f0bdc1b75a8637a8b8b" #Generated by weatherappapi
city = "Jaypur"
url = f"http://api.openweathermap.org/data/2.5/weather?q={city}&appid={API_KEY}&units=metric"

response = requests.get(url)
if response.status_code == 200:
    data = response.json()

    #Accessing and printing values
    print(f"City :{data['name']}") #Prints city name
    print(f"Country: {data['sys']['country']}") #prints country
    print(f"Temparature: {data['main']['temp']}°C") #prints temparature
    print(f"Condition: {data['weather'][0]['main']}") #prints weather condition
else:
    print("Failed to fetch data.")


'''
Output :
City : Jaypur
Country: IN
Temparature: 35°C
Condition: Partly Cloudy
'''
